version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    #network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:4571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,lambda,kinesis
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker_reuse}
      - DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG-1}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
      - KINESIS_PROVIDER=kinesalite
      - PORT_WEB_UI=8888
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # se você tiver o docker rootless use outro sock -> echo $DOCKER_HOST
      - "localstack_data:/tmp/localstack/data"
    networks:
          default:

volumes:
    localstack_data:
networks:
    default:
        external:
            name: localstack-tutorial
